apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dwh-kubertest2
    app: kubertest2-web
  name: kubertest2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dwh-kubertest2
      app: kubertest2-web  
      tier: frontend
      track: stable      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwh-kubertest2
        app: kubertest2-web  
        tier: frontend
        track: stable      
    spec:
      volumes:
      - name: volumelogs
        hostPath:
          path: /mnt/logs

      containers:
      - env:
        - name: LOG_DIR
          value: /var/logs/
        #image: gitlab.neva.loc:5050/firsttestgroup/kubertest2/webapp:latest
        image: gitlab.neva.loc:5050/dmitriygroup/web-app-soa-template/catalogapi:latest
        imagePullPolicy: Always
        name: kubertest2
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/log/n3dwh/
            name: volumelogs        
      imagePullSecrets:
        - name: gitlab-credentials1
---
apiVersion: v1
kind: Service
metadata:
  name: kubertest2
  labels:
    app: kubertest2-web
spec:
  clusterIP: None
  ports:
   - name: http
     protocol: TCP
     port: 8000
  selector:
   app: kubertest2-web




