version: '3.4'

services:
  catalogapi:
    image: catalogapi
    build:
      context: ./services/catalogapi
      dockerfile: ./Dockerfile
    ports:
    - 5142:80

  spa:
    image: spa
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
    - 3000:80