version: '3.4'

volumes:
    keycloak-data:
    
services:
  keycloakdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data\
    ports:
      - 54321:5432