version: '3.4'

services:

  catalogapi:
    image: catalogapi
    build:
      context: ./services/catalogapi
      dockerfile: ./Dockerfile

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./frontend/nginx/security.conf:/etc/nginx/security.conf
      - ./frontend/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./etc/certs/https.crt:/etc/nginx/certs/https.crt
      - ./etc/certs/key.pem:/etc/nginx/certs/key.pem
    environment:
    - BACKEND_CATALOG=catalogapi
    - BASE_URL=localhost
    ports:
      - 80:80
      - 443:443