version: '3.4'
services:
  sso:
    image: sso
    build: 
      context: services/sso
      dockerfile: ./Dockerfile
      args: 
        - SUB_PATH=/
        - HOSTNAME=localhost
        - IS_PROXIED=false
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - DB_HOST=localhost
        - DB_NAME=keycloak
    volumes:
      - ./services/sso/realm.json:/opt/keycloak/data/import/realm.json
    environment:
      - MAINPAGE_SPA_CLIENT_SECRET=AGVacqRHpG5PXbUXpaQ0kKiXartkh5LB
      - MAINPAGE_SPA_CLIENT_HREF=http://localhost:3000/
      - MAINPAGE_SPA_CLIENT_REDIRECT_URI=http://localhost:3000/
    command: start-dev --import-realm 
    ports:
      - 8080:8080
      - 8443:8443  




    